//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jogo()
        {
            this.Comentarios = new HashSet<Comentario>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SelecaoCasaId { get; set; }
        public Nullable<int> PlacarCasa { get; set; }
        public Nullable<int> SelecaoVisitanteId { get; set; }
        public Nullable<int> PlacarVisitante { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> RodadaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentario> Comentarios { get; set; }
        public virtual Rodada Rodada { get; set; }
        public virtual Seleco Seleco { get; set; }
        public virtual Seleco Seleco1 { get; set; }
    }
}
