//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificacoesUsuario
    {
        public int Id { get; set; }
        public string Status { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> NotificacaoId { get; set; }
    
        public virtual Notificaco Notificaco { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
