//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sessao5Entities : DbContext
    {
        public Sessao5Entities()
            : base("name=Sessao5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comentario> Comentarios { get; set; }
        public virtual DbSet<Jogadore> Jogadores { get; set; }
        public virtual DbSet<Jogo> Jogos { get; set; }
        public virtual DbSet<Notificaco> Notificacoes { get; set; }
        public virtual DbSet<NotificacoesUsuario> NotificacoesUsuarios { get; set; }
        public virtual DbSet<Posico> Posicoes { get; set; }
        public virtual DbSet<Rodada> Rodadas { get; set; }
        public virtual DbSet<Seleco> Selecoes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
